version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  dev:
    image: registry.gitlab.com/smart-home-the-verse/433mhz-middle-man:dev
    container_name: 433mhz-middle-man-dev
    depends_on:
      - mosquitto
    build: 
      context: .
      target: dev
    volumes: 
      - .:/usr/src/app
    environment: 
      - NODE_ENV=dev
      - MQTT_BROKER=mosquitto
      - ADDRESS=0.0.0.0
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: [ "npm", "run", "dev" ]

  web:
    image: registry.gitlab.com/smart-home-the-verse/433mhz-middle-man:latest
    container_name: 433mhz-middle-man
    environment: 
      - MQTT_BROKER=192.168.42.45
      - ADDRESS=0.0.0.0
    build:
      context: .
      target: prod
    ports:
      - 80:3000
    restart: on-failure